version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "4000:3000"
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
